### ISSUE TITLE
Properly roll back database when something goes terribly wrong

### ISSUE THREAD

**Issue by suchow** [suchow/Wallace#224]
#243, an issue where we fail to properly sanitize input in incoming HTTP requests, causes bigger problems for Wallace than we would hope. In particular, if malformed input is received, our app crashes in the middle of transaction and gives the error:

`InternalError: (InternalError) current transaction is aborted, commands ignored until end of transaction block`

I believe this is the same issue and the answer to it:

http://stackoverflow.com/questions/2979369/databaseerror-current-transaction-is-aborted-commands-ignored-until-end-of-tra

We don't know how to do this.

**Comment by alecpm** [comment]
It looks like you're creating a DB session separate from the psiturk one when an experiment starts up, but your not integrating it into the request management process. This means that all requests to the same thread will use the same session/transaction, which is not good.  The session should probably only live as long as each request.

It should be quite easy to handle the transaction management similarly to psiturk as a first step toward addressing these issues. However, I'm not quite convinced the psiturk DB session management follows SQLAlchemy best practices either. I'll create a pull request with the initial fix shortly.

I do wonder why Psiturk doesn't use Flask-SQLAlchemy, which handles the DB sessions automatically among other things.

**Comment by alecpm** [comment]
The pull request above will roll back any uncommitted changes at the end of the Flask request cycle, it will not roll back any committed changes that happened during the request (there are cases with multiple commit calls in a single route).  If you need more complex transaction handling, that will require a more complex refactoring to pull the explicit commits out of the route handlers, and wrap everything in a context manager or similar.

I'm assuming those commits (along with the autoflush) are there because you intend to make queries within the request that should return newly added/updated data.  That should be fine, as long as no successful commit call on its own results in an inconsistent state for your application, if later commits were to fail.

**Comment by alecpm** [comment]
As mentioned in the call, I do wonder if it's necessary for Wallace to provide a separate parallel DB session along with the one provided by PsiTurk, since they appear to be intended to use the same database.

**Comment by thomasmorgan** [comment]
@alecpm I am wondering if this solves the problem with malformed arguments arriving? (see #243)

In short, this was a problem because one malformed argument would paralyze the whole app. But now that each request opens its own transaction and we have the ability to rollback in the case of an error, my guess is that the worst that will happen is that that particular transaction will fail and be rolled back to its most recent commit (or back to the start of the transaction if there haven't been any commits in that transaction).

The reason I ask is because currently we have lots of code checking that arguments are of the correct form. For instance in the following code from custom.py, we receive `node_id` as an optional argument and we need to make sure it is an int:

```
            node_id = request.values["node_id"]
            if not node_id.isdigit():
                msg = "/node GET request, non-numeric node_id"
                exp.log("Error: {}".format(node_id), key)
                data = {
                    "status": "error",
                    "html": error_page(error_type=msg)
                }
                return Response(
                    dumps(data),
                    status=400,
                    mimetype='application/json')
```

My hope is that, with your fixes, we can remove this check entirely as even if `node_id` is malformed nothing too wrong will happen. So the code would now just be:

```
node_id = request.values["node_id"]
```

Does this sound advisable to you? The downside, as far as I can see is that it won't send the custom error page, it will just return a status 500 error. However, we could handle that on the client side if needs be...

@suchow what do you think?

**Comment by cewing** [comment]
@thomasmorgan if individual requests are properly isolated from each other, then failure in one request will not bring the app to its knees.  But as I've commented on your PR #247, it's also possible with args that arrive via URL rather than by Query string, to ensure at least a minimal validity by way of type assertions in flask route declarations.  That will also help.  

On the front end, implementing error handling in the js app for those cases where a 500 or a 404 is raised by the backend is a great idea.

**Comment by thomasmorgan** [comment]
@cewing Thanks Cris. I have implemented the url approach for mandatory arguments, however, my issue is now with optional arguments. These cannot be specified in the url without being mandatory, right?

**Comment by cewing** [comment]
@thomasmorgan, no.  As far as I know, flask is not able to have optional args in a route.  So for those, you do need to have some code that handles validation.  However, this validation could be handled as individual functions that are called within a view function.  That way you can write the validation code once instead of needing to add it to every view you create.  That reduces repetition and by proxy, the number of places you need to change code if you need to change how a particular case is handled.
