### ISSUE TITLE
What do these usage stats say about necessary server resources?

### ISSUE THREAD

**Issue by suchow** [suchow/Wallace#245]
![screenshot 2015-10-25 00 23 16](https://cloud.githubusercontent.com/assets/613981/10714047/a365b946-7aae-11e5-837f-c4a5c4215510.jpg)

![screenshot 2015-10-25 00 24 37](https://cloud.githubusercontent.com/assets/613981/10714052/cabfd2d8-7aae-11e5-9730-df25ae682e71.jpg)

Earlier, we were running our experiment on 8 Performance-M web dynos and 2 Performance-M worker dynos. As an experiment, I halved the number of each kind. Above are the stats AFTER halving the dyno resources.

I think the above stats suggest we can safely halve the number of web dynos again (making the average load ~1 and the max ~4) and decrease the number of worker dynos considerably, to at most 1 Performance-M, but probably even down to 1 2X dyno.

Does that sound right?

**Comment by alecpm** [comment]
These proposed dyno reductions seem reasonable to me given the load profile.  I do recommend optionally using New Relic to provide some deeper performance metrics and tracing.

https://elements.heroku.com/addons/newrelic
http://newrelic.com/python/flask
https://docs.newrelic.com/docs/agents/python-agent/supported-features/python-background-tasks

**Comment by thomasmorgan** [comment]
We have a basic stress-testing framework for Wallace, and I've been testing out the code on the pull request. The tests work by putting up the app on heroku and then locally creating threads that aggressively ping the server, mimicking the behavior of a participants who made lightning fast decisions (this uses Requests: http://docs.python-requests.org/en/latest/). With 2 performance-m web dynos and 1 performance-m worker dyno the app handles 16 pseudo-participants totally fine. Above this (say with 20) I start getting these errors on my local machine:

```
Traceback (most recent call last):
  File "/Users/Tom/Documents/Wallace/Rogers/tests.py", line 90, in autobot
    information2 = requests.get(url + '/info', params=args, headers=headers)
  File "/Users/Tom/.virtualenvs/wallace6/lib/python2.7/site-packages/requests-2.2.1-py2.7.egg/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Users/Tom/.virtualenvs/wallace6/lib/python2.7/site-packages/requests-2.2.1-py2.7.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Tom/.virtualenvs/wallace6/lib/python2.7/site-packages/requests-2.2.1-py2.7.egg/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Tom/.virtualenvs/wallace6/lib/python2.7/site-packages/requests-2.2.1-py2.7.egg/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Tom/.virtualenvs/wallace6/lib/python2.7/site-packages/requests-2.2.1-py2.7.egg/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='w42f1c5c2-e8d4-49f5-a914-5b2b.herokuapp.com', port=80): Max retries exceeded with url: /info?info_id=58&node_id=1497&participant_id=0%3A0 (Caused by <class 'httplib.BadStatusLine'>: '')
```

The server seems totally fine though, so I'm guessing **it** can handle 20 pseudo-participants, but my machine can't cope with running them. I'm posting this here incase Cris or Alec have any suggestions as to why this might be. My guess is that either the app refuses the connection because it is getting too many requests too quickly, or I'm overusing the ports on my machine and it gets unhappy.

I should note though that 16 pseudo-participants is probably a similar load to about 40 actual participants and so 2 performance-m web dynos is probably sufficient

**Comment by alecpm** [comment]
It might help to take advantage of the connection pooling/reuse and persistent connections that requests.Session provides for each of your threads (http://docs.python-requests.org/en/latest/user/advanced/).  Perhaps something like:

    def autobot(session, url, i):
        ...
        session.get(...)
        ...
        session.post(...)
        ...
    
    # create worker threads
    threads = []
    for i in range(autobots):
        with requests.Session() as session:
            t = threading.Thread(target=autobot, args=(session, url, i,))
            threads.append(t)
            t.start()

Where the `autobot` method uses the passed in session object (unique per thread) instead of the requests object directly.  That way each set of serialized requests operates with a single session and potentially reuses a single persistent connection, making it less likely you'll exhaust the pool.

That will make your test more efficient, but I don't think it will fix this specific issue, which seems to result from retrying a failed request repeatedly (BadStatusLine exception, which implies the `info` endpoint is sending back an invalid HTTP status code somewhere). The `autobot` code has a bare except and appears to log and then ignore the exception.  I think that could result in repeating the same failed requests ad infinitum.  If you want to continue despite an exception, I would suggest being more explicit about the exceptions you intend to catch and ignore (as Cris has mentioned elsewhere).  It would probably also make sense to break out of the while loop when an exception occurs, at least for most exceptions, and especially for any unanticipated ones, to prevent repeated failures.

I would also suggest using the python logging module here, rather than print statements; specifically the logging.exception() method which will automatically log the traceback.  Cris will have more info on that in another ticket, but there's a good tutorial here: https://docs.python.org/2/howto/logging.html

One larger thing to consider, if the intent here is primarily to provide load testing, python has some good frameworks for doing HTTP load testing, which should be more efficient, and take care of a lot of the thread and request management.  I recommend looking at locust.io (http://docs.locust.io/en/latest/what-is-locust.html and https://speakerdeck.com/cgbystrom/load-testing-with-locust?slide=24)

**Comment by thomasmorgan** [comment]
Thanks Alec, I'll try the changes you suggest now and let you know how it goes

**Comment by thomasmorgan** [comment]
@alecpm Your suggestion worked excellently. I just ran 36 autobots with no problems whatsoever.

The BadStatusLine does indeed seem a bit odd, but from previous googling sessions on this topic I gather that Error is a bit of a catch all for requests and is actually not very informative.

Thanks!
